[
  {
    postalCode: 123456,
    name: "Charmander",
    floor: "02",
    unit: "15",
    homeNumber: 62222222,
    mobileNumber: 81234567,
    medicalConditions: ["Heart Condition", "Stays Alone"],
    bluetoothDeviceID: "1234",
    statusList: [{ task: "Buy Food", isDone: false }],
    volunteer_ids: [],
  },
  {
    postalCode: 123456,
    name: "Squirtle",
    floor: "12",
    unit: "15",
    homeNumber: 61111111,
    mobileNumber: 87654321,
    medicalConditions: ["Feels Lonely", "Staying Alive"],
    bluetoothDeviceID: "4321",
    statusList: [
      { task: "Buy Food", isDone: false },
      { task: "See Doctor", isDone: false },
    ],
    volunteer_ids: [],
  },
  {
    postalCode: 654321,
    name: "Bulbasaur",
    floor: "05",
    unit: "05",
    homeNumber: 63333333,
    mobileNumber: 12345678,
    medicalConditions: ["COPD", "Dementia"],
    bluetoothDeviceID: "1324",
    statusList: [
      { task: "Shower", isDone: false },
      { task: "Find a job", isDone: true },
    ],
    volunteer_ids: [],
  },
  {
    postalCode: 654321,
    name: "Ivysaur",
    floor: "11",
    unit: "11",
    homeNumber: 64444444,
    mobileNumber: 12348765,
    medicalConditions: ["Diabetes", "Cancer"],
    bluetoothDeviceID: "1423",
    statusList: [
      { task: "Take the train", isDone: true },
      { task: "Dance", isDone: false },
    ],
    volunteer_ids: [],
  },
  {
    postalCode: 111111,
    name: "Cyndaquil",
    floor: "12",
    unit: "15",
    homeNumber: 66666666,
    mobileNumber: 13245768,
    medicalConditions: ["Diabetes", "Cancer"],
    bluetoothDeviceID: "1423",
    statusList: [
      { task: "Take the train", isDone: true },
      { task: "Dance", isDone: false },
    ],
    volunteer_ids: [],
  },
];

module.exports = seedElderly;
